apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: dsmsjavasampleapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dsmsjavasampleapp 
    spec:
      containers:
        - name: dsmsjavasampleapp 
          image: madhuvdockersample.azurecr.io/dsmsjavasampleapp 
          ports:
          - containerPort: 80